<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">SLIDE</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">Add Slide</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-lg-6">
						<?php
						$form->prepare();
						echo $this->form()->openTag($form);
						?>
							<div class="form-group">
								<?php echo $this->formElement($form->get('id'))?>
							</div>
						<div class="form-group">
							<label>Note</label>
								 <?php echo $this->formElement($form->get('description'))?>
							</div>
						<div class="form-group">
							<label>Image</label> 
								<?php echo $this->formElement($form->get('image'))?>
							</div>
							<?php echo $this->formElement($form->get('submit')); ?>
							<button type="reset" class="btn btn-default">Reset</button>
						<?php echo $this->form()->closeTag($form);?>
					</div>
					<div class="col-lg-6">
						<div class="panel panel-default">
							<div class="panel-heading">Image Pro</div>
							<!-- /.panel-heading -->
							<div class="panel-body">
								<div class="img_hinh" style ="display: none;">
									<img class="hienhinh" src="" height="100px" width="150px" /> 
								</div>
							</div>
							<!-- .panel-body -->
						</div>
						<!-- /.panel -->
					</div>
				</div>
				<!-- /.row (nested) -->
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>
<script type="text/javascript">
    $(document).ready(function(){
    $(".file").change(function(){
    var file = this.files[0];
    var imagefile = file.type;
    var match= ["image/jpeg","image/png","image/jpg"];
    if(!((imagefile==match[0]) || (imagefile==match[1]) || (imagefile==match[2])))
    {
        return false;
    }
    else
    {
        var reader = new FileReader();
        reader.onload = imageIsLoaded;
        reader.readAsDataURL(this.files[0]);
    }
    });
    });
    function imageIsLoaded(e) {
    $(".file").css("color","green");
    $('.img_hinh').css("display", "block");
    $('.hienhinh').attr('src', e.target.result);
    $('.hienhinh').attr('width', '480px');
    $('.hienhinh').attr('height', '230px');
    };
</script>