<script type="text/javascript">
      $(document).ready(function(){
        $('.thong').click(function(){
          var id = $(this).parent().data('id');
          $('input[name="idpro"]').val(id);
        });
      });
</script>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Tables</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<p class="fa fa-heart"></p>
				List Slide <a href="/admin/slide/add">
					<button type="button" class="btn btn-success">
						<span class="glyphicon glyphicon-send"></span> Add Slide
					</button>
				</a> | <a href="#">
					<button type="button" class="btn btn-primary">
						<span class="glyphicon glyphicon-plus-sign"></span> Import Exe
					</button>
				</a>
			</div>

			<!-- /.panel-heading -->
			<div class="panel-body">
				<table width="100%"
					class="table table-striped table-bordered table-hover"
					id="dataTables-example">
					<thead>
						<tr>
							<th>ID</th>
							<th style="width: 30px">Image</th>
							<th>Description</th>
							<th>Link</th>
							<th>Option</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($slide as $sl):?>
						<tr class="odd gradeX" data-id="<?php echo $sl->id;?>">
							<td><?php echo $sl->id;?></td>
							<td><img style="width: 300px; height:120px" src="/img/<?php echo $sl->image;?>"></td>
							<td><?php echo $sl->description;?></td>
							<td><?php echo $sl->link;?></td>
							<td class="thong text-center"><a
								href="/admin/slide/add/<?php echo $sl->id;?>"> Edit </a>| <a
								data-id="#" data-toggle="modal"
								data-target="#myModal"> Delete</a>
							</td>
						</tr>
						<?php endforeach;?>
					</tbody>
				</table>
				<!-- /.table-responsive -->
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel">Delete Type products</h4>
			</div>
			<form class="form-horizontal" action="slide/delete" method="POST" role="form">
				<div class="modal-body">
					<div class="col-sm-12 text-center">Bạn Muốn Xóa Loại Sản Phẩm:</div>
					<div class="col-sm-12 text-center">
						<div class="form-group">
							<div class="col-xs-12">
								<input type="text" class="form-control" name="idpro" readonly="readonly">
							</div>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="modal-footer">
					<input type="submit" name="deleteproduct" class="btn btn-success"
						value="Delete">
				</div>
			</form>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->