<!DOCTYPE HTML>
<html>
<head>
<title>New Shop Thong Pro</title>
<!--css-->
<link href="<?php echo $this->basePath();?>/css/bootstrap.css" rel="stylesheet" type="text/css" media="all"/>
<link href="<?php echo $this->basePath();?>/css/style.css" rel="stylesheet" type="text/css" media="all" />
<link href="<?php echo $this->basePath();?>/css/font-awesome.css" rel="stylesheet">
<!--css-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="New Shop Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<script src="<?php echo $this->basePath();?>/js/jquery.min.js"></script>
<link href='<?php echo $this->basePath();?>//fonts.googleapis.com/css?family=Cagliostro' rel='stylesheet' type='text/css'>
<link href='<?php echo $this->basePath();?>//fonts.googleapis.com/css?family=Open+Sans:400,800italic,800,700italic,700,600italic,600,400italic,300italic,300' rel='stylesheet' type='text/css'>
<!--search jQuery-->
	<script src="<?php echo $this->basePath();?>/js/main.js"></script>
<!--search jQuery-->
<script src="<?php echo $this->basePath();?>/js/responsiveslides.min.js"></script>
<script src="<?php echo $this->basePath();?>/js/angular.min.js"></script>
<link href="<?php echo $this->basePath();?>/css/coreSlider.css" rel="stylesheet" type="text/css">
<script src="<?php echo $this->basePath();?>/js/coreSlider.js"></script>
 <script>
    $(function () {
      $("#slider").responsiveSlides({
      	auto: true,
      	nav: true,
      	speed: 500,
        namespace: "callbacks",
        pager: true,
      });
    });
 </script>
 <!--mycart-->
<script type="text/javascript" src="<?php echo $this->basePath();?>/js/bootstrap-3.1.1.min.js"></script>
 <!-- cart -->
<script src="<?php echo $this->basePath();?>/js/simpleCart.min.js"></script>
<!-- cart -->
  <!--start-rate-->
<script src="<?php echo $this->basePath();?>/js/jstarbox.js"></script>
	<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/jstarbox.css" type="text/css" media="screen" charset="utf-8" />
		<script type="text/javascript">
			jQuery(function() {
			jQuery('.starbox').each(function() {
				var starbox = jQuery(this);
					starbox.starbox({
					average: starbox.attr('data-start-value'),
					changeable: starbox.hasClass('unchangeable') ? false : starbox.hasClass('clickonce') ? 'once' : true,
					ghosting: starbox.hasClass('ghosting'),
					autoUpdateAverage: starbox.hasClass('autoupdate'),
					buttons: starbox.hasClass('smooth') ? false : starbox.attr('data-button-count') || 5,
					stars: starbox.attr('data-star-count') || 5
					}).bind('starbox-value-changed', function(event, value) {
					if(starbox.hasClass('random')) {
					var val = Math.random();
					starbox.next().text(' '+val);
					return val;
					} 
				})
			});
		});
		</script>
<!--//End-rate-->
</head>
<body>
		<!--header-->
		<?php echo $this->render('partial/header.phtml'); ?>
		<!--header-->
		<!--banner-->
		<?php echo $this->render('partial/slider.phtml'); ?>
		<!--banner-->
			<!--content-->
		<div class="content">
			<?php echo $this->content; ?>
		</div>
		<!--content-->
		<!---footer--->
			<?php echo $this->render('partial/footer.phtml'); ?>
		<!---footer--->
		<?php echo $this->render('modal/modal.phtml');?>

</body>
</html>