<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">PRODUCTS</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">Add products</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-lg-6">
						<?php $form->prepare();
						echo $this->form()->openTag($form);
						?>
							<div class="form-group">
								<?php echo $this->formElement($form->get('id'))?>
							</div>
							<div class="form-group">
								<label>Name :</label>
								<?php echo $this->formElement($form->get('name'))?>
								<?php echo $this->formElementErrors()->render($form->get('name'));?>
							</div>
							<div class="form-group">
								<label>Unit Price</label>
								 <?php echo $this->formElement($form->get('unit_price'))?>
							</div>
							<div class="form-group">
								<label>Promotion Price</label> 
								<?php echo $this->formElement($form->get('promotion_price'))?>
							</div>
							<div class="form-group">
								<label>Note</label>
								<?php echo $this->formElement($form->get('description'))?>
							</div>
							<div class="form-group">
								<label>Type</label>
									<?php echo $this->formElement($form->get('id_type')); ?>
							</div>
							<div class="form-group">
								<label>New / Sale / Of New</label>
									<?php echo $this->formElement($form->get('new')); ?>
							</div>
							<div class="form-group">
								<label>Image Products</label>
								<?php echo $this->formElement($form->get('image[]'))?>
							</div>
							<div class="form-group">
								<label></label>
								<div id="list-image" class="col-sm-12"></div>
							</div>
							<div class="form-group">
								<label>Sex</label>
								<div class="radio">
									<label> <input type="radio" name="optionsRadios"
										id="optionsRadios1" value="option1" checked>Men
									</label>
								</div>
								<div class="radio">
									<label> <input type="radio" name="optionsRadios"
										id="optionsRadios2" value="option2">Woment
									</label>
								</div>
							</div>

							<?php echo $this->formElement($form->get('submit')); ?>
							<button type="reset" class="btn btn-default">Reset</button>
						<?php echo $this->form()->closeTag($form);?>
					</div>
					<div class="col-lg-6">
						<div class="col-lg-12">
							<div class="panel panel-green">
								<div class="panel-heading">Default Panel</div>
								<div class="panel-body">
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
										Vestibulum tincidunt est vitae ultrices accumsan. Aliquam
										ornare lacus adipiscing, posuere lectus et, fringilla augue.</p>
								</div>
								<div class="panel-footer">Panel Footer</div>
							</div>
						</div>
						<!-- /.col-lg-4 -->
						<div class="col-lg-12">
							<!-- /.panel -->
							<div class="chat-panel panel panel-default">
								<div class="panel-heading">
									<i class="fa fa-comments fa-fw"></i> Chat
									<div class="btn-group pull-right">
										<button type="button"
											class="btn btn-default btn-xs dropdown-toggle"
											data-toggle="dropdown">
											<i class="fa fa-chevron-down"></i>
										</button>
										<ul class="dropdown-menu slidedown">
											<li><a href="#"> <i class="fa fa-refresh fa-fw"></i> Refresh
											</a></li>
											<li><a href="#"> <i class="fa fa-check-circle fa-fw"></i>
													Available
											</a></li>
											<li><a href="#"> <i class="fa fa-times fa-fw"></i> Busy
											</a></li>
											<li><a href="#"> <i class="fa fa-clock-o fa-fw"></i> Away
											</a></li>
											<li class="divider"></li>
											<li><a href="#"> <i class="fa fa-sign-out fa-fw"></i> Sign
													Out
											</a></li>
										</ul>
									</div>
								</div>
								<!-- /.panel-heading -->
								<div class="panel-body">
									<ul class="chat">
										<li class="left clearfix"><span class="chat-img pull-left"> <img
												src="http://placehold.it/50/55C1E7/fff" alt="User Avatar"
												class="img-circle" />
										</span>
											<div class="chat-body clearfix">
												<div class="header">
													<strong class="primary-font">Jack Sparrow</strong> <small
														class="pull-right text-muted"> <i
														class="fa fa-clock-o fa-fw"></i> 12 mins ago
													</small>
												</div>
												<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
													Curabitur bibendum ornare dolor, quis ullamcorper ligula
													sodales.</p>
											</div></li>
										<li class="right clearfix"><span class="chat-img pull-right">
												<img src="http://placehold.it/50/FA6F57/fff"
												alt="User Avatar" class="img-circle" />
										</span>
											<div class="chat-body clearfix">
												<div class="header">
													<small class=" text-muted"> <i class="fa fa-clock-o fa-fw"></i>
														13 mins ago
													</small> <strong class="pull-right primary-font">Bhaumik
														Patel</strong>
												</div>
												<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
													Curabitur bibendum ornare dolor, quis ullamcorper ligula
													sodales.</p>
											</div></li>
										<li class="left clearfix"><span class="chat-img pull-left"> <img
												src="http://placehold.it/50/55C1E7/fff" alt="User Avatar"
												class="img-circle" />
										</span>
											<div class="chat-body clearfix">
												<div class="header">
													<strong class="primary-font">Jack Sparrow</strong> <small
														class="pull-right text-muted"> <i
														class="fa fa-clock-o fa-fw"></i> 14 mins ago
													</small>
												</div>
												<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
													Curabitur bibendum ornare dolor, quis ullamcorper ligula
													sodales.</p>
											</div></li>
										<li class="right clearfix"><span class="chat-img pull-right">
												<img src="http://placehold.it/50/FA6F57/fff"
												alt="User Avatar" class="img-circle" />
										</span>
											<div class="chat-body clearfix">
												<div class="header">
													<small class=" text-muted"> <i class="fa fa-clock-o fa-fw"></i>
														15 mins ago
													</small> <strong class="pull-right primary-font">Bhaumik
														Patel</strong>
												</div>
												<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
													Curabitur bibendum ornare dolor, quis ullamcorper ligula
													sodales.</p>
											</div></li>
									</ul>
								</div>
								<!-- /.panel-body -->
								<div class="panel-footer">
									<div class="input-group">
										<input id="btn-input" type="text"
											class="form-control input-sm"
											placeholder="Type your message here..." /> <span
											class="input-group-btn">
											<button class="btn btn-warning btn-sm" id="btn-chat">Send</button>
										</span>
									</div>
								</div>
								<!-- /.panel-footer -->
							</div>
						</div>

					</div>
				</div>
				<!-- /.row (nested) -->
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<div class="col-lg-12">
		<div class="panel panel-red">
			<div class="panel-heading">Default Panel</div>
			<div class="panel-body">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
					Vestibulum tincidunt est vitae ultrices accumsan. Aliquam ornare
					lacus adipiscing, posuere lectus et, fringilla augue.</p>
			</div>
			<div class="panel-footer">Panel Footer</div>
		</div>
	</div>
<!-- /.col-lg-12 -->
</div>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    var img = $('<img style="width: 100%">'); //Equivalent: $(document.createElement('img'))
                    img.attr('src', e.target.result);
                    var div = '<div class="col-sm-4 item-image" >' + img.prop('outerHTML') + '<button style="position: absolute;background: #fa6f57;border: none;right: 15px;top: 0px;color: white;">×</button></div>';
                    //console.log(div);
                    $('#list-image').append(div);
                    $(".item-image button").click(function () {
                        $(this).parent().remove();
                    })
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#imgInp").change(function () {
            readURL(this);
        });
    });
</script>