<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">TYPE PRODUCTS</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">Add type products</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-lg-6">
						<?php
						$form->prepare();
						echo $this->form()->openTag($form);
						?>
							<div class="form-group">
								<?php echo $this->formElement($form->get('id'))?>
							</div>
						<div class="form-group">
							<label>Name :</label>
								<?php echo $this->formElement($form->get('nametype'))?>
								<?php echo $this->formElementErrors()->render($form->get('nametype'));?>
							</div>
						<div class="form-group">
							<label>Note</label>
								 <?php echo $this->formElement($form->get('description'))?>
							</div>
						<div class="form-group">
							<label>Sex</label> 
								<?php echo $this->formElement($form->get('sex'))?>
							</div>
							<?php echo $this->formElement($form->get('submit')); ?>
							<button type="reset" class="btn btn-default">Reset</button>
						<?php echo $this->form()->closeTag($form);?>
					</div>
					<div class="col-lg-6">
						<div class="panel panel-default">
							<div class="panel-heading">Dismissable Alerts</div>
							<!-- /.panel-heading -->
							<div class="panel-body">
								<div class="alert alert-success alert-dismissable">
									<button type="button" class="close" data-dismiss="alert"
										aria-hidden="true">&times;</button>
									Lorem ipsum dolor sit amet, consectetur adipisicing elit. <a
										href="#" class="alert-link">Alert Link</a>.
								</div>
								<div class="alert alert-info alert-dismissable">
									<button type="button" class="close" data-dismiss="alert"
										aria-hidden="true">&times;</button>
									Lorem ipsum dolor sit amet, consectetur adipisicing elit. <a
										href="#" class="alert-link">Alert Link</a>.
								</div>
								<div class="alert alert-warning alert-dismissable">
									<button type="button" class="close" data-dismiss="alert"
										aria-hidden="true">&times;</button>
									Lorem ipsum dolor sit amet, consectetur adipisicing elit. <a
										href="#" class="alert-link">Alert Link</a>.
								</div>
								<div class="alert alert-danger alert-dismissable">
									<button type="button" class="close" data-dismiss="alert"
										aria-hidden="true">&times;</button>
									Lorem ipsum dolor sit amet, consectetur adipisicing elit. <a
										href="#" class="alert-link">Alert Link</a>.
								</div>
							</div>
							<!-- .panel-body -->
						</div>
						<!-- /.panel -->
					</div>
				</div>
				<!-- /.row (nested) -->
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<div class="col-lg-12">
		<div class="panel panel-red">
			<div class="panel-heading">Default Panel</div>
			<div class="panel-body">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
					Vestibulum tincidunt est vitae ultrices accumsan. Aliquam ornare
					lacus adipiscing, posuere lectus et, fringilla augue.</p>
			</div>
			<div class="panel-footer">Panel Footer</div>
		</div>
	</div>
	<!-- /.col-lg-12 -->
</div>