<div class="new-arrivals-w3agile">
	<div class="container">
		<h2 class="tittle">New Product</h2>
		<div class="arrivals-grids">
			<div class="col-md-3 arrival-grid simpleCart_shelfItem bt-product">
				<div class="grid-arr">
					<div class="grid-arrival">
						<figure>
							<a href="#" class="new-gri" data-toggle="modal"
								data-target="#myModal1">
								<div class="grid-img">
									<img src="<?php echo $this->basePath('/img/p6.jpg')?>"
										class="img-responsive" alt="">
								</div>
								<div class="grid-img">
									<img src="img/p5.jpg" class="img-responsive" alt="">
								</div>
							</a>
						</figure>
					</div>
					<div class="ribben">
						<p>NEW</p>
					</div>
					<div class="ribben1">
						<p>SALE</p>
					</div>
					<div class="block">
						<div class="starbox small ghosting"></div>
					</div>
					<div class="women">
						<h6>
							<a href="single.html">Sed ut perspiciatis unde</a>
						</h6>
						<span class="size">XL / XXL / S </span>
						<p>
							<del>$100.00</del>
							<em class="item_price">$70.00</em>
						</p>
						<a href="#" data-text="Add To Cart" class="my-cart-b item_add">Add
							To Cart</a>
					</div>
				</div>
			</div>
			<div class="col-md-3 arrival-grid simpleCart_shelfItem bt-product">
				<div class="grid-arr">
					<div class="grid-arrival">
						<figure>
							<a href="#" class="new-gri" data-toggle="modal"
								data-target="#myModal2">
								<div class="grid-img">
									<img src="img/p7.jpg" class="img-responsive" alt="">
								</div>
								<div class="grid-img">
									<img src="img/p8.jpg" class="img-responsive" alt="">
								</div>
							</a>
						</figure>
					</div>
					<div class="ribben2">
						<p>OUT OF STOCK</p>
					</div>
					<div class="block">
						<div class="starbox small ghosting"></div>
					</div>
					<div class="women">
						<h6>
							<a href="single.html">Sed ut perspiciatis unde</a>
						</h6>
						<span class="size">XL / XXL / S </span>
						<p>
							<del>$100.00</del>
							<em class="item_price">$70.00</em>
						</p>
						<a href="#" data-text="Add To Cart" class=" my-cart-b item_add">Add
							To Cart</a>
					</div>
				</div>
			</div>
			<div class="col-md-3 arrival-grid simpleCart_shelfItem bt-product">
				<div class="grid-arr">
					<div class="grid-arrival">
						<figure>
							<a href="#" class="new-gri" data-toggle="modal"
								data-target="#myModal3">
								<div class="grid-img">
									<img src="img/p10.jpg" class="img-responsive" alt="">
								</div>
								<div class="grid-img">
									<img src="img/p9.jpg" class="img-responsive" alt="">
								</div>
							</a>
						</figure>
					</div>
					<div class="ribben1">
						<p>SALE</p>
					</div>
					<div class="block">
						<div class="starbox small ghosting"></div>
					</div>
					<div class="women">
						<h6>
							<a href="single.html">Sed ut perspiciatis unde</a>
						</h6>
						<span class="size">XL / XXL / S </span>
						<p>
							<del>$100.00</del>
							<em class="item_price">$70.00</em>
						</p>
						<a href="#" data-text="Add To Cart" class="my-cart-b item_add">Add
							To Cart</a>
					</div>
				</div>
			</div>
			<div class="col-md-3 arrival-grid simpleCart_shelfItem bt-product">
				<div class="grid-arr">
					<div class="grid-arrival">
						<figure>
							<a href="#" class="new-gri" data-toggle="modal"
								data-target="#myModal4">
								<div class="grid-img">
									<img src="img/p11.jpg" class="img-responsive" alt="">
								</div>
								<div class="grid-img">
									<img src="img/p12.jpg" class="img-responsive" alt="">
								</div>
							</a>
						</figure>
					</div>
					<div class="block">
						<div class="starbox small ghosting"></div>
					</div>
					<div class="women">
						<h6>
							<a href="single.html">Sed ut perspiciatis unde</a>
						</h6>
						<span class="size">XL / XXL / S </span>
						<p>
							<del>$100.00</del>
							<em class="item_price">$70.00</em>
						</p>
						<a href="#" data-text="Add To Cart" class="my-cart-b item_add">Add
							To Cart</a>
					</div>
				</div>
			</div>
			<div class="col-md-3 arrival-grid simpleCart_shelfItem bt-product">
				<div class="grid-arr">
					<div class="grid-arrival">
						<figure>
							<a href="#" class="new-gri" data-toggle="modal"
								data-target="#myModal1">
								<div class="grid-img">
									<img src="<?php echo $this->basePath('/img/p6.jpg')?>"
										class="img-responsive" alt="">
								</div>
								<div class="grid-img">
									<img src="img/p5.jpg" class="img-responsive" alt="">
								</div>
							</a>
						</figure>
					</div>
					<div class="ribben">
						<p>NEW</p>
					</div>
					<div class="ribben1">
						<p>SALE</p>
					</div>
					<div class="block">
						<div class="starbox small ghosting"></div>
					</div>
					<div class="women">
						<h6>
							<a href="single.html">Sed ut perspiciatis unde</a>
						</h6>
						<span class="size">XL / XXL / S </span>
						<p>
							<del>$100.00</del>
							<em class="item_price">$70.00</em>
						</p>
						<a href="#" data-text="Add To Cart" class="my-cart-b item_add">Add
							To Cart</a>
					</div>
				</div>
			</div>
			<div class="col-md-3 arrival-grid simpleCart_shelfItem bt-product">
				<div class="grid-arr">
					<div class="grid-arrival">
						<figure>
							<a href="#" class="new-gri" data-toggle="modal"
								data-target="#myModal2">
								<div class="grid-img">
									<img src="img/p7.jpg" class="img-responsive" alt="">
								</div>
								<div class="grid-img">
									<img src="img/p8.jpg" class="img-responsive" alt="">
								</div>
							</a>
						</figure>
					</div>
					<div class="ribben2">
						<p>OUT OF STOCK</p>
					</div>
					<div class="block">
						<div class="starbox small ghosting"></div>
					</div>
					<div class="women">
						<h6>
							<a href="single.html">Sed ut perspiciatis unde</a>
						</h6>
						<span class="size">XL / XXL / S </span>
						<p>
							<del>$100.00</del>
							<em class="item_price">$70.00</em>
						</p>
						<a href="#" data-text="Add To Cart" class=" my-cart-b item_add">Add
							To Cart</a>
					</div>
				</div>
			</div>
			<div class="col-md-3 arrival-grid simpleCart_shelfItem bt-product">
				<div class="grid-arr">
					<div class="grid-arrival">
						<figure>
							<a href="#" class="new-gri" data-toggle="modal"
								data-target="#myModal3">
								<div class="grid-img">
									<img src="img/p10.jpg" class="img-responsive" alt="">
								</div>
								<div class="grid-img">
									<img src="img/p9.jpg" class="img-responsive" alt="">
								</div>
							</a>
						</figure>
					</div>
					<div class="ribben1">
						<p>SALE</p>
					</div>
					<div class="block">
						<div class="starbox small ghosting"></div>
					</div>
					<div class="women">
						<h6>
							<a href="single.html">Sed ut perspiciatis unde</a>
						</h6>
						<span class="size">XL / XXL / S </span>
						<p>
							<del>$100.00</del>
							<em class="item_price">$70.00</em>
						</p>
						<a href="#" data-text="Add To Cart" class="my-cart-b item_add">Add
							To Cart</a>
					</div>
				</div>
			</div>
			<div class="col-md-3 arrival-grid simpleCart_shelfItem bt-product">
				<div class="grid-arr">
					<div class="grid-arrival">
						<figure>
							<a href="#" class="new-gri" data-toggle="modal"
								data-target="#myModal4">
								<div class="grid-img">
									<img src="img/p11.jpg" class="img-responsive" alt="">
								</div>
								<div class="grid-img">
									<img src="img/p12.jpg" class="img-responsive" alt="">
								</div>
							</a>
						</figure>
					</div>
					<div class="block">
						<div class="starbox small ghosting"></div>
					</div>
					<div class="women">
						<h6>
							<a href="single.html">Sed ut perspiciatis unde</a>
						</h6>
						<span class="size">XL / XXL / S </span>
						<p>
							<del>$100.00</del>
							<em class="item_price">$70.00</em>
						</p>
						<a href="#" data-text="Add To Cart" class="my-cart-b item_add">Add
							To Cart</a>
					</div>
				</div>
			</div>
			<div class="clearfix"></div>
			
		</div>
	</div>
</div>